name: djed
description: The Dart implementation of the Djed, the formally verified Crypto-Backed Pegged Algorithmic Stablecoin
version: 0.1.1
repository: https://github.com/ilap/djed-dart/

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.2
  benchmark_harness: ^2.1.0

dependencies: 
  tuple: ^2.0.0
